### ISSUE TITLE
Expose bitness of the OS

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/PlatformAbstractions#38]
This came up in https://github.com/aspnet/Hosting/pull/726 where it was suggested that we also include the OS bitness. We can potentially use `System.Environment.Is64BitOperatingSystem` and `System.Runtime.InteropServices.RuntimeInformation.OSArchitecture` for this.

**Comment by pranavkm** [comment]
There's an issue with the `System.Runtime.InteropServices.RuntimeInformation` package which doesn't allow it to be consumed in net45x applications. This will be fixed in RTM (https://github.com/dotnet/corefx/issues/7863). The plan is to switch to `RuntimeInformation` going forward rather than add features to `IRuntimeInformation`

**Comment by moozzyk** [comment]
`System.Environment.Is64BitOperatingSystem` does not seem like a good fit for ARM.

**Comment by JunTaoLuo** [comment]
`System.Environment.Is64BitOperatingSystem` is available for full CLR only, `System.Runtime.InteropServices.RuntimeInformation.OSArchitecture` has 4 values `Arm`,`Arm64`,`x86`,`x64`,

**Comment by moozzyk** [comment]
Makes sense then.

**Comment by Eilon** [comment]
@BrennanConroy can you figure out what we need to do here?

**Comment by muratg** [comment]
Related: https://github.com/aspnet/PlatformAbstractions/issues/34

**Comment by BrennanConroy** [comment]
There isn't anything to actually do here?

**Comment by pranavkm** [comment]
I don't think so. We could close this.
